<?php
/***********************************************/
/* THIS IS A GROUP INCLUDE FOR ALL MODEL FILES */
/* > this should be a subset of the full model */
/***********************************************/
//user
require_once('model/user/User.inc.php');
//content
require_once('model/content/CmsPage.inc.php');
require_once('model/content/CmsPageEvent.inc.php');
require_once('model/content/CmsPageEventType.inc.php');
require_once('model/content/CmsPageStatus.inc.php');
require_once('model/content/CmsSection.inc.php');
require_once('model/content/CmsSite.inc.php');
require_once('model/content/SiteContact.inc.php');
require_once('model/content/SiteContactStatus.inc.php');
require_once('model/content/SiteContactType.inc.php');
//customer
require_once('model/customer/EmailList.inc.php');
require_once('model/customer/Subscription.inc.php');
require_once('model/customer/SubscriptionEvent.inc.php');
require_once('model/customer/SubscriptionEventType.inc.php');
//email
require_once('model/email/Email.inc.php');
require_once('model/email/EmailBody.inc.php');
require_once('model/email/EmailEvent.inc.php');
require_once('model/email/EmailEventType.inc.php');
require_once('model/email/EmailRecipient.inc.php');
require_once('model/email/EmailRecipientType.inc.php');
require_once('model/email/EmailStatus.inc.php');
require_once('model/email/EmsTemplate.inc.php');
//image
require_once('model/image/Image.inc.php');
require_once('model/image/ImageType.inc.php');
//partner
require_once('model/partner/Partner.inc.php');
require_once('model/partner/PartnerConfig.inc.php');
require_once('model/partner/PartnerConfigType.inc.php');
//provider
require_once('model/provider/HourRules.inc.php');
require_once('model/provider/Provider.inc.php');
require_once('model/provider/ProviderType.inc.php');
require_once('model/provider/ProviderEvent.inc.php');
require_once('model/provider/ProviderEventType.inc.php');
require_once('model/provider/ProviderImage.inc.php');
require_once('model/provider/ProviderImageType.inc.php');
require_once('model/provider/ProviderSpokenLanguage.inc.php');
require_once('model/provider/ProviderStatus.inc.php');
require_once('model/provider/StripeAccount.inc.php');
//reference
require_once('model/reference/BaseType.inc.php');
require_once('model/reference/ContentType.inc.php');
require_once('model/reference/DayOfWeek.inc.php');
//service
require_once('model/service/Service.inc.php');
require_once('model/service/ServiceCategory.inc.php');
?>
